version: '3'
services:
#   redis:
#     image: redis
#     ports:
#       - "6379:6379"
#     networks:
#       - docker-default
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-weather-app
    env_file: .env
    # links:
    #   - redis
    ports:
      - 3000:3000
#     networks:
#       - docker-default
#     volumes:
#       - '.:/home/node'
# networks:
#   docker-default:
